name: "Compute Matrix Action"
description: "Computes matrix"
inputs:
  BUILD_TYPE:
    description: "The build type"
    required: true
outputs:
  MATRIX:
    description: "Computed matrix"
    value: ${{ steps.compute-matrix.outputs.MATRIX }}
runs:
  using: "composite"
  steps:
    - name: Compute matrix
      id: compute-matrix
      run: |
        MATRIX=$(ci/compute-mx.sh)
        echo "MATRIX=${MATRIX}" | tee -a ${GITHUB_OUTPUT}
      env:
        BUILD_TYPE: ${{ inputs.BUILD_TYPE }}
      shell: bash
