name: Build Multi-Arch Docker Image
description: Create and push a multi-arch Docker image manifest
inputs:
  ARCHES:
    required: true
    type: string
  CUDA_VER:
    required: true
    type: string
  LINUX_VER:
    required: true
    type: string
  PYTHON_VER:
    required: true
    type: string
  IMAGE_REPO:
    required: true
    type: string
  BUILD_TYPE:
    required: true
    type: string
  IMAGE_NAME:
    required: true
    type: string
  GPUCIBOT_DOCKERHUB_USER:
    required: true
    type: string
  GPUCIBOT_DOCKERHUB_TOKEN:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.GPUCIBOT_DOCKERHUB_USER }}
        password: ${{ inputs.GPUCIBOT_DOCKERHUB_TOKEN }}

    - name: Create multiarch manifest
      env:
        IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
        ARCHES: ${{ inputs.ARCHES }}
        LINUX_VER: ${{ inputs.LINUX_VER }}
        CUDA_VER: ${{ inputs.CUDA_VER }}
        PYTHON_VER: ${{ inputs.PYTHON_VER }}
        IMAGE_REPO: ${{ inputs.IMAGE_REPO }}
        BUILD_TYPE: ${{ inputs.BUILD_TYPE }}
      run: .github/actions/build-multiarch-manifest/create-multiarch-manifest.sh
      shell: bash
