name: Delete Temporary Images
description: Delete temporary images from DockerHub
inputs:
  CUDA_VER:
    required: true
    type: string
  LINUX_VER:
    required: true
    type: string
  PYTHON_VER:
    required: true
    type: string
  IMAGE_REPO:
    required: true
    type: string
  ARCHES:
    required: true
    type: string
  BUILD_TYPE:
    required: true
    type: string
  IMAGE_NAME:
    required: true
    type: string
  GPUCIBOT_DOCKERHUB_USER:
    required: true
    type: string
  GPUCIBOT_DOCKERHUB_TOKEN:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Remove temporary images
      run: |
        HUB_TOKEN=$(
            curl -s -H "Content-Type: application/json" \
            -X POST \
            -d "{\"username\": \"${{ inputs.GPUCIBOT_DOCKERHUB_USER }}\", \"password\": \"${{ inputs.GPUCIBOT_DOCKERHUB_TOKEN }}\"}" \
            https://hub.docker.com/v2/users/login/ | jq -r .token \
        )

        image_name="${{ inputs.IMAGE_NAME }}"
        org=${image_name%%/*}
        temp=${image_name#*/}
        repo=${temp%%:*}
        tag=${image_name##*:}

        for arch in $(echo '${{ inputs.ARCHES }}' | jq .[] -r); do
            curl --fail-with-body -i -X DELETE \
            -H "Accept: application/json" \
            -H "Authorization: JWT $HUB_TOKEN" \
            "https://hub.docker.com/v2/repositories/$org/$repo/tags/$tag-$arch/"
        done
