name: Delete Temporary Images
description: Delete temporary images from DockerHub
inputs:
  CUDA_VER:
    required: true
    type: string
  LINUX_VER:
    required: true
    type: string
  PYTHON_VER:
    required: true
    type: string
  IMAGE_REPO:
    required: true
    type: string
  ARCHES:
    required: true
    type: string
  BUILD_TYPE:
    required: true
    type: string
  IMAGE_NAME:
    required: true
    type: string
  GPUCIBOT_DOCKERHUB_USER:
    required: true
    type: string
  GPUCIBOT_DOCKERHUB_TOKEN:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Remove temporary images
      run: .github/actions/delete-temp-images/remove-temp-images.sh
      shell: bash
      env:
        GPUCIBOT_DOCKERHUB_USER: ${{ inputs.GPUCIBOT_DOCKERHUB_USER }}
        GPUCIBOT_DOCKERHUB_TOKEN: ${{ inputs.GPUCIBOT_DOCKERHUB_TOKEN }}
        IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
        ARCHES: "${{ inputs.ARCHES }}"
