name: Build cibuildwheel 11.5.1 images

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  # amd64 manylinux builds on centos7
  manylinux2014-amd64-ctk115:
    uses: ./.github/workflows/docker-buildx-native-multiarch.yml
    secrets: inherit
    with:
      push: true
      submodules: 'recursive'
      docker-build-amd64: "BUILD_IMAGE=rapidsai/manylinux2014:cuda-devel-11.5.1-centos7-amd64 ./build.sh"
