name: build and publish RAPIDS cibuildwheel images

on:
  workflow_call:
    inputs:
      push:
        required: true
        type: boolean

jobs:
  docker-cibuildwheel:
    name: cibuildwheel ${{ matrix.base-image }} ${{ matrix.labels[2] }}
    runs-on: ${{ matrix.labels }}
    strategy:
      matrix:
        include:
          - labels: [self-hosted, linux, arm64, cpu4]
            base-image: nvidia/cuda:11.5.1-runtime-ubuntu20.04

          - labels: [self-hosted, linux, amd64, cpu4]
            base-image: nvidia/cuda:11.5.1-runtime-ubuntu18.04
    env:
      DOCKERHUB_USERNAME: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Build rapidsai/cibuildwheel container
        run: >
          docker build
          -f cibuildwheel.Dockerfile
          --build-arg CPU_ARCH=${{ matrix.labels[2] }}
          --build-arg BASE_IMAGE=${{ matrix.base-image }}
          --build-arg CIBUILDWHEEL_VERSION=2.8.0
          -t rapidsai/cibuildwheel_${{ matrix.labels[2] }}
          --pull
          .
      - name: Push rapidsai/cibuildwheel containers to DockerHub
        if: ${{ inputs.push }}
        run: docker push rapidsai/cibuildwheel_${{ matrix.labels[2] }}
  docker-citestwheel:
    name: citestwheel ${{ matrix.base-image }} ${{ matrix.labels[2] }}
    runs-on: ${{ matrix.labels }}
    strategy:
      matrix:
        include:
          - labels: [self-hosted, linux, arm64, cpu4]
            base-image: nvidia/cuda:11.5.1-devel-ubuntu20.04

          - labels: [self-hosted, linux, amd64, cpu4]
            base-image: nvidia/cuda:11.5.1-devel-ubuntu18.04
    env:
      DOCKERHUB_USERNAME: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Build rapidsai/citestwheel container
        run: >
          docker build
          -f citestwheel.Dockerfile
          --build-arg CPU_ARCH=${{ matrix.labels[2] }}
          --build-arg BASE_IMAGE=${{ matrix.base-image }}
          -t rapidsai/citestwheel_${{ matrix.labels[2] }}
          --pull
          ./context-citestwheel
      - name: Push rapidsai/citestwheel containers to DockerHub
        if: ${{ inputs.push }}
        run: docker push rapidsai/citestwheel_${{ matrix.labels[2] }}
