name: Build RAPIDS pip wheel CI images

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  all-containers:
    uses: ./.github/workflows/docker-buildx-native-multiarch.yml
    secrets: inherit
    with:
      push: true
      build_type: branch
