on:
    pull_request:
      types: [closed]

jobs:
    compute-matrix:
      runs-on: ubuntu-latest
      outputs:
        MATRIX: ${{ steps.compute-matrix.outputs.MATRIX }}
      steps:
        - uses: actions/checkout@v3
        - name: Compute Matrix Action
          id: compute-matrix
          uses: ./.github/actions/compute-matrix
          with:
            BUILD_TYPE: "pull-request"
            PR_NUM: ${{ github.event.pull_request.number }}
    delete-imgs:
      needs: compute-matrix
      strategy:
        matrix: ${{ fromJSON(needs.compute-matrix.outputs.MATRIX) }}
      uses: ./.github/workflows/delete-temp-images.yml
      with:
        ARCHES: ${{ toJSON(matrix.ARCHES) }}
        CUDA_VER: ${{ matrix.CUDA_VER }}
        IMAGE_REPO: ${{ matrix.IMAGE_REPO }}
        LINUX_VER: ${{ matrix.LINUX_VER }}
        PYTHON_VER: ${{ matrix.PYTHON_VER }}
        BUILD_TYPE: "pull-request"
        USED_REPO: ${{ matrix.USED_REPO }}
        TAG_PREFIX: ${{ matrix.TAG_PREFIX }}
      secrets: inherit
  