name: PR build of RAPIDS pip wheel CI images

on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  cibw-containers:
    uses: ./.github/workflows/docker-multiarch-native.yml
    secrets: inherit
    with:
      matrix_script: "./ci/compute-matrix.sh"
      push: false
      build_type: branch
