name: publish

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-cibuildwheel-images:
    uses: ./.github/workflows/build-and-publish-cibuildwheel.yml
    with:
      push: true
    secrets: inherit
  build-citestwheel-images:
    uses: ./.github/workflows/build-and-publish-citestwheel.yml
    with:
      push: true
    secrets: inherit
